### ISSUE TITLE
Code no longer works

### ISSUE THREAD

**Issue by Peelz4Dead** [Maeeen/drawful-2-colors#1]
Hi sir your code doesn't seem to work anymore could you please try to update it?

**Comment by Maeeen** [comment]
Hi !

I wasn't really expecting any attention from this small script but, here I made an update !

Works for the lastest version, you can check it (on [master](https://github.com/Maeeen/drawful-2-colors)) !

(See my own PR (because too lazy to clone everything) [here](https://github.com/Maeeen/drawful-2-colors/pull/2) )
